sudo: false

language: go
go:
  - "1.11"
  - tip

go_import_path: ekyu.moe/h2s

install:
  - go get -t ./...
  - go generate ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -SsL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION = 1.11

notifications:
  email:
    on_success: never
    on_failure: always
